### PR TITLE
Added UseForwardedHeaders

### PR DESCRIPTION
**Pull request by stuart-bass-bjss**

### CODE REVIEW

**Comment by bjss-chris** [comment]
Do we need this one? Will just setting the `ASPNETCORE_FORWARDEDHEADERS_ENABLED` environment variable as described [here](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1#forwarded-headers-middleware-improvements) not work?

**Comment by stuart-bass-bjss** [comment]
> Do we need this one? Will just setting the `ASPNETCORE_FORWARDEDHEADERS_ENABLED` environment variable as described [here](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1#forwarded-headers-middleware-improvements) not work?

As Chris has pointed out, this is not needed, so I'm abandoning the change.

**Comment by stuart-bass-bjss** [comment]
Abandoning as not needed

**Comment by stuart-bass-bjss** [comment]
closing as not needed

**Comment by stuart-bass-bjss** [comment]
close

**Comment by stuart-bass-bjss** [comment]
close

**Comment by stuart-bass-bjss** [comment]
close

**Comment by sam-roberts-bjss** [comment]
As requested, closing this PR.

**Pull request closed without merging**
